#!/usr/bin/python
# -*- encoding: utf-8 -*-
'''
@file         : analysis.py
@author       : Yell
@brief        : 
@version      : 0.1
@date         : 2024-02-28 09:30:20
'''

from data_manager.aimp_dm import AimpDataManager
from backend.backend_flow_innovus import BackendFlowInnovus

from multiprocessing import Process

class BackendTask():
    """"""
    def __init__(self, data_manager : AimpDataManager):
        self.data_manager = data_manager

    def run_backend_flow(self):
        #run backend flow after imp
        #if run innovus, the flow waits for the result generated by the server with IP 192.168.224.155 where innovus & pt installed
        backend_flow = BackendFlowInnovus(self.data_manager.get_task_name())
        while backend_flow.is_success() is True:
            return True
        
        return False

