################################################################################
#  definition generated by config json
################################################################################

################################################################################
#  task setting
################################################################################
set TASK run_eda

################################################################################
#  workspace setting
################################################################################
set WORKSPACE /home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1

################################################################################
#  src script setting
################################################################################
set SRC_SCRIPT /home/huangzengrong/gitee/ai-eda/resource/script

################################################################################
#  eda tool
#  optional value : iEDA innovus pt
################################################################################
set EDA_TOOL innovus

################################################################################
#  common setting
################################################################################
set VERSION V1

################################################################################
#  process setting
################################################################################
set PROCESS_NODE t28

################################################################################
#  path setting
################################################################################
#design
set DESIGN asic_top

set DEF_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_place.def"
set VERILOG_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_place.v"
set SDC_PATH "/home/zhuangchunan/proj/iEDA1216_T28/bes_data/sta/sdc/asic_top_CTS_MAX.sdc"
set SPEF_PATH ""
set MP_TCL_PATH ""


################################################################################
#  flow setting, including steps as below
#  edi
#  floorplan 
#     set VERILOG_INPUT_PATH "/home/zhuangchunan/proj/iEDA1216_T28/bes_data/syn/netlist/asic_top_0324.syn.v.gz"
#  prePlace
#     set DEF_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_floorplan.def"
#     set VERILOG_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_floorplan.v"
#  place
#     set DEF_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_prePlace.def"
#     set VERILOG_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_prePlace.v"
#  CTS
#     set DEF_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_place.def"
#     set VERILOG_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_place.v"
#  route
#     set DEF_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_CTS.def"
#     set VERILOG_INPUT_PATH "/home/huangzengrong/gitee/ai-eda/workspace/ws_ysyx4_mp_1/output/innovus/result/asic_top_CTS.v"
#  eco
################################################################################
set PRE_STEP prePlace
set STEP route

################################################################################
#  FPT setting
################################################################################
set FPT_STATE on

################################################################################
#  parameter setting
################################################################################