################################################################################
#  tcl main
#  generated by gen_script in AiEDA
################################################################################
source <definition完整路径>/definition.tcl
source ${SRC_SCRIPT}/${EDA_TOOL}/${EDA_TOOL}.tcl