#!/usr/bin/python
# -*- encoding: utf-8 -*-
'''
@file         : backend_flow.py
@author       : Yell
@brief        : 
@version      : 0.1
@date         : 2024-02-28 09:31:20
'''
from flow.run_flow_innovus import RunFlowInnovus

class BackendFlowInnovus():
    """run backend flow for aimp"""
    def __init__(self, workspace_path : str):
        self.workspace_path = workspace_path
        
    def run_innovus_flow(self):
        """run innovus flow for workspace"""
        flow_manager = RunFlowInnovus(self.workspace_path)
        return flow_manager.run()
    
    def is_success(self):
        """search for the result generated by innovus"""
        
        return True
