
################################################################################
#  definition generated by config json
################################################################################

################################################################################
#  task setting
################################################################################
set TASK run_eda

################################################################################
#  workspace setting
################################################################################
set WORKSPACE /data/project_share/dataset_baseline/gcd/workspace

################################################################################
#  src script setting
################################################################################
set SRC_SCRIPT /home/huangzengrong/aimp/benchmark/AiEDA/third_party/resource/innovus/scripts

################################################################################
#  eda tool setting, optional value : iEDA innovus pt
################################################################################
set EDA_TOOL innovus

################################################################################
#  common setting
################################################################################
set VERSION V1

################################################################################
#  process setting
################################################################################
set PROCESS_NODE t28
set PROJECT gcd
set DESIGN gcd

################################################################################
#  path setting
################################################################################
set LEF_PATHS "/data/project_share/process_node/T28_lib/tech/tsmcn28_9lm6X2ZUTRDL.tlef \
          /data/project_share/process_node/dataset_baseline/lef_min/PLLTS28HPMLAINT.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140opplvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140lvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140uhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140hvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140oppuhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts5n28hpcplvta256x32m4fw_130a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140cg.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140oppuhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140mbhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140ulvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140uhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts5n28hpcplvta64x100m2fw_130a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140hvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140oppulvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140mb.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140cgcwhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140lvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tpbn28v_9lm.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts5n28hpcplvta64x128m2f_130a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140uhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140mblvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140cgcw.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140mbhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tpbn28v.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts5n28hpcplvta64x128m2fw_130a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140lvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140ulvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140opphvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140cgehvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140mb.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tphn28hpcpgv18_9lm.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts5n28hpcplvta64x88m2fw_130a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140mb.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140cghvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140opp.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140cghvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140oppehvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts1n28hpcplvtb2048x48m8sw_180a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts5n28hpcplvta64x92m2fw_130a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140mblvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140cg.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140opplvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140cg.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140opphvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts1n28hpcplvtb512x128m4sw_180a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts5n28hpcplvta64x96m2fw_130a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140opphvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140hvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140oppuhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140cguhvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140opp.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts1n28hpcplvtb512x64m4sw_180a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts6n28hpcplvta2048x32m8sw_130a.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp30p140opp.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp35p140oppulvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140ehvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/tcbn28hpcplusbwp40p140opplvt.lef \
          /data/project_share/process_node/dataset_baseline/lef_min/ts1n28hpcplvtb8192x64m8sw_180a.lef"

set LIB_PATHS "/data/project_share/process_node/dataset_baseline/lib_min/tcbn28hpcplusbwp40p140lvtssg0p81v125c.lib \
          /data/project_share/process_node/dataset_baseline/lib_min/tcbn28hpcplusbwp30p140lvtssg0p81v125c.lib \
          /data/project_share/process_node/dataset_baseline/lib_min/tcbn28hpcplusbwp40p140ssg0p81v125c.lib \
          /data/project_share/process_node/dataset_baseline/lib_min/tcbn28hpcplusbwp40p140hvtssg0p81v125c.lib"

set SDC_PATH /data/project_share/dataset_baseline/gcd/syn_netlist/gcd.sdc
set SPEF_PATH ""
set DEF_INPUT_PATH /data/project_share/dataset_baseline/gcd/workspace/output/iEDA/result/gcd_route.def
set VERILOG_INPUT_PATH /data/project_share/dataset_baseline/gcd/workspace/output/iEDA/result/gcd_route.v
set DEF_OUTPUT_PATH /data/project_share/dataset_baseline/gcd/workspace/output/innovus/result/gcd_drc.def
set VERILOG_OUTPUT_PATH /data/project_share/dataset_baseline/gcd/workspace/output/innovus/result/gcd_drc.v
set GUIDE_PATH /data/project_share/dataset_baseline/gcd/workspace/output/innovus/result/gcd_route.guide
set MP_TCL_PATH ""

################################################################################
#  step setting
################################################################################
set PRE_STEP route
set STEP drc

################################################################################
#  set if save innovus design as step data, and support restoreDesign
################################################################################
set SAVE_DESIGN 1

################################################################################
#  fpt setting
################################################################################
set FPT_STATE on

################################################################################
#  drc setting
################################################################################
set DRC_REPORT_MAX_NUM 1000000
set DRC_REPORT_PATH /data/project_share/dataset_baseline/gcd/workspace/output/iEDA/rpt/gcd_drc.rpt
